fix: GitHub waffles action by pinning markupsafe (#118)
Pin the markupsafe package since the `soft_unicode` has been removed
which was causing the action to fail with an import error:

```
ImportError: cannot import name 'soft_unicode' from 'markupsafe'
```